### ISSUE TITLE
Issue: Profile page not loading new updated image and other user values

### ISSUE THREAD

**Issue by sanjaygyawali1** [manjulatern/GymProject#7]
Steps to replicate:

1. After login, go to the profile page.
2. Select a new profile image
3. Click on "Update Profile Image"

Current Behavior:
The profile page is wrongly loaded, as the updated profile image is not seen. The values on User Profile is not loaded as well.
After again clicking on the profile link, all the information is loaded along with the updated image.

Expected Behavior:
The profile page should be loaded with the updated image and all the values when the profile update is done.

**Comment by manjulatern** [comment]
profile_image method in gymadmin.views is loading profile.html page as
`template = loader.get_template('profile.html')`
`context = {'uploaded_file_url': uploaded_file_url}`
`return HttpResponse(template.render(context,request)) `

can be changed to
`return redirect('/profile')`

**Comment by manjulatern** [comment]
closed #8
